WEB_ASP_TP3/Models/LivroViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WEB_ASP_TP3.Models
{
    public class LivroViewModel
    {

        public int Id { get; set; }

        [Required(ErrorMessage = "Coloque o Titulo")]
        [StringLength(50, ErrorMessage = "Você só pode adicionar até 50 caracteres")]
        public string Titulo { get; set; }

        [Required(ErrorMessage = "Coloque o Autor")]
        [StringLength(50, ErrorMessage = "Você só pode adicionar até 50 caracteres")]
        public string Autor { get; set; }

        [Required(ErrorMessage = "Coloque a Editora")]
        [StringLength(50, ErrorMessage = "Você só pode adicionar até 50 caracteres")]
        public string Editora { get; set; }

        [Required(ErrorMessage = "Coloque o Ano")]
        [RegularExpression("[0-9]{4}", ErrorMessage ="O ano só pode conter 4 caracteres")]
        public int Ano { get; set; }

        //[Required(ErrorMessage = "Coloque a Anotação")]
        [StringLength(100, ErrorMessage = "Você só pode adicionar até 100 caracteres")]
        public string Anotacao { get; set; }
    }
}

WEB_ASP_TP3/Controllers/LivroController.cs
using WEB_ASP_TP3.Models;
using WEB_ASP_TP3.Repository;
using System.Linq;
using System.Web.Mvc;
using WEB_ASP_TP3.Domain;

namespace WEB_ASP_TP3.Controllers
{
    public class LivroController : Controller
    {

        private readonly ILivroRepository repository;
        public LivroController(ILivroRepository repository) {

            this.repository = repository;
        }



        // GET: Livro Lista
        public ActionResult index()
        {
            //var repository = new LivroRepository();

            var Livros = repository.GetAllLivros();

            return View(
                Livros.Select(a => new LivroViewModel()
                {
                    Id = a.Id,
                    Titulo = a.Titulo,
                    Autor = a.Autor,
                    Editora = a.Editora,
                    Ano = a.Ano,
                    Anotacao = a.Anotacao
                }));

        }


        public ActionResult Create()
        {
            return View();
        }


        // POST: Livro/Create
        [HttpPost]
        public ActionResult Create(LivroViewModel livro)
        {
            if (ModelState.IsValid)
            {
                //var repository = new LivroRepository();

                repository.CreateLivro(new Livro()
                {
                    Titulo = livro.Titulo,
                    Autor = livro.Autor,
                    Editora = livro.Editora,
                    Ano = livro.Ano,
                    Anotacao = livro.Anotacao
                });

                return RedirectToAction("index");
            }
                return View();
        }

        // GET: Livro/Detalhe/5
        public ActionResult Detalhe(int Id)
        {
            //var repository = new LivroRepository();
            var Livro = repository.GetOneLivro(Id);
            if (Livro == null)
            {
                return HttpNotFound();
            }

            return View(Livro);
        }

        public ActionResult Edit(int Id)
        {
            //var repository = new LivroRepository();
            var Livro = repository.GetOneLivro(Id);
            if (Livro == null)
            {
                return HttpNotFound();
            }

            return View(Livro);
        }

        // POST: Livro/Edit/5
        [HttpPost]
        public ActionResult Edit(Livro livro)
        {
            
                if (ModelState.IsValid)
                {
                    //var repository = new LivroRepository();
                    repository.EditLivro(livro);
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(livro);
                }
                         
        }

        public ActionResult PreviewDelete(int Id)
        {
            //var repository = new LivroRepository();
            var Livro = repository.GetOneLivro(Id);
            if (Livro == null)
            {
                return HttpNotFound();
            }

            return View(Livro);
        }


        public ActionResult Delete(int Id)
        {
        try
            {
               //var repository = new LivroRepository();


        repository.DeleteLivro(Id);
                    // TODO: Add delete logic here
                
                return RedirectToAction("index");
    }
            catch
            {
                return View();
}
        }

        // POST: Livro/Delete/5
        [HttpPost]
        public ActionResult Delete()
        {

                return View();
        }
    }
}

WEB_ASP_TP3/Views/Livro/Create.cshtml
@model WEB_ASP_TP3.Models.LivroViewModel

@{
    ViewBag.Title = "Adicionando livro";
}

<h2>Adicionar</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
       
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-1" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Autor, htmlAttributes: new { @class = "control-label col-md-1" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Autor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Autor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Editora, htmlAttributes: new { @class = "control-label col-md-1" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Editora, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Editora, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ano, htmlAttributes: new { @class = "control-label col-md-1" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ano, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ano, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Anotacao, htmlAttributes: new { @class = "control-label col-md-1" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Anotacao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Anotacao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-1 col-md-10">
                <input type="submit" value="Adicionar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

WEB_ASP_TP3/Views/Livro/Delete.cshtml
@model IEnumerable<WEB_ASP_TP3.Models.LivroViewModel>

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Voce tem certeza?</h3>

        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |

            <input type="button" class="btn btn-info" value="Cancelar" onclick="location.href='@Url.Action("index", "Livro")'" />
        </div>
</div>

WEB_ASP_TP3/Views/Livro/Detalhe.cshtml
@model WEB_ASP_TP3.Domain.Livro

@{
    ViewBag.Title = "Detalhe";
}

<div>
    <h3>Detalhes do livro @Model.Titulo</h3>
    <hr />
    <div class="form-horizontal">

        <div class="form-group">
            <div class="col-md-10">
                <dt style="font-size: 20px;">
                    @Html.DisplayNameFor(model => model.Titulo)
                </dt>
                <dd style="font-size: 18px">
                    @Html.DisplayFor(model => model.Titulo)
                </dd>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                <dt  style="font-size: 20px;">
                    @Html.DisplayNameFor(model => model.Autor)
                </dt>
                <dd style="font-size: 18px">
                    @Html.DisplayFor(model => model.Autor)
                </dd>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                <dt style="font-size: 20px;">
                    @Html.DisplayNameFor(model => model.Editora)
                </dt>
                <dd style="font-size: 18px">
                    @Html.DisplayFor(model => model.Editora)
                </dd>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                <dt style="font-size: 20px;">
                    @Html.DisplayNameFor(model => model.Ano)
                </dt>
                <dd style="font-size: 18px">
                    @Html.DisplayFor(model => model.Ano)
                </dd>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                <dt style="font-size: 20px;">
                    @Html.DisplayNameFor(model => model.Anotacao)
                </dt>
                <dd style="font-size: 18px">
                    @Html.DisplayFor(model => model.Anotacao)
                </dd>
            </div>
        </div>

    </div>    
</div>
<p>
    <input type="button" class="btn btn-warning" value="Editar" onclick="location.href='@Url.Action("Edit", "Livro", new { id = Model.Id })'" />
    @Html.ActionLink("Voltar", "index", new { id = Model.Id }, htmlAttributes: new { @class = "btn btn-primary" })
</p>

WEB_ASP_TP3/Views/Livro/Edit.cshtml
@model WEB_ASP_TP3.Domain.Livro

@{
    ViewBag.Title = "Edit";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h3>Editando livro @Model.Titulo de id @Model.Id</h3>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-1" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Autor, htmlAttributes: new { @class = "control-label col-md-1" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Autor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Autor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Editora, htmlAttributes: new { @class = "control-label col-md-1" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Editora, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Editora, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ano, htmlAttributes: new { @class = "control-label col-md-1" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ano, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ano, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Anotacao, htmlAttributes: new { @class = "control-label col-md-1" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Anotacao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Anotacao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-1 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-success" />
                <input type="button" class="btn btn-info" value="Cancelar" onclick="location.href='@Url.Action("index", "Livro")'" />
            </div>
        </div>
    </div>
}

WEB_ASP_TP3/Views/Livro/PreviewDelete.cshtml
@model WEB_ASP_TP3.Domain.Livro

@{
    ViewBag.Title = "Delete";
}

<h2>Excluir</h2>
<h3>Você deseja excluir este registro?</h3>

    
    <hr />
<dl class="dl-horizontal">
    <dt>
        @Html.DisplayNameFor(model => model.Titulo)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.Titulo)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.Autor)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.Autor)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.Editora)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.Editora)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.Ano)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.Ano)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.Anotacao)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.Anotacao)
    </dd>

</dl>
@using (Html.BeginForm())
    {
        <p>
            @Html.ActionLink("Delete", "Delete", new { id = Model.Id }, htmlAttributes: new { @class = "btn btn-danger" })
            @Html.ActionLink("Voltar", "index", new { id = Model.Id }, htmlAttributes: new { @class = "btn btn-primary" })
        </p>
    }
    

WEB_ASP_TP3/Views/Livro/index.cshtml
@model IEnumerable<WEB_ASP_TP3.Models.LivroViewModel>


@{
    ViewBag.Title = "Lista";
}

<h2>Lista de livros</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Titulo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Autor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Editora)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ano)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Titulo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Autor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Editora)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ano)
            </td>
            <td>
                <input type="button" class="btn btn-warning" value="Editar" onclick="location.href='@Url.Action("Edit", "Livro", new { id = item.Id })'" />
                <input type="button" class="btn btn-info" value="Detalhe" onclick="location.href='@Url.Action("Detalhe", "Livro", new { id = item.Id })'" />
                <input type="button" class="btn btn-danger" value="Deletar" onclick="location.href='@Url.Action("PreviewDelete", "Livro", new { id = item.Id })'" />
            </td>
        </tr>
    }

</table>

WEB_ASP_TP3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>


                @Html.ActionLink("Início", "index", new { area = "" }, new { @class = "navbar-brand" })

                @Html.ActionLink("Adicionar", "create", new { area = "" }, new { @class = "navbar-brand" })               
               
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - WEB_ASP_TP3 ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>